import LiquidGlassEffect from "@/Components/LiquidGlassEffect/LiquidGlassEffect";

export const metadata = {
  title: "Grant Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <LiquidGlassEffect />
      {children}
    </>
  );
}
