export const metadata = {
  title: "Grant Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return children;
}
