import { Ubuntu, K2D } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

const k2d = K2D({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-k2d",
});

export const metadata = {
  title: "Grant Portfolio",
  description: "Generated by create next app",
};


async function getSiteSettings() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}/api/globals/site-settings?depth=1`, {
    cache: "no-store",
  });

  if (!res.ok) return null;
  return res.json();
}

async function getContactInfo() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}/api/globals/contact-info?depth=1`, {
    cache: "no-store",
  });

  if (!res.ok) return null;
  return res.json();
}

export default async function SiteLayout({ children }) {
  const [data, contactInfo] = await Promise.all([
    getSiteSettings(),
    getContactInfo(),
  ]);


  return (
    <html lang="en">
      <body className={`${ubuntu.variable} ${k2d.variable} antialiased`}>
        <div className="container mx-auto px-5 sm:px-10 lg:px-14">
          <Navbar navItems={data ? data.navItems : []} logo={data?.logo} />
          {children}
        </div>
        <Footer
          footerDesc={data?.footerDescription}
          navItems={data?.navItems ?? []}
          offices={contactInfo?.offices ?? []}
          socialLinks={contactInfo?.socialLinks ?? {}}
        />
      </body>
    </html>
  );
}
