import { Montserrat, Playfair_Display } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import LiquidGlassEffect from "@/Components/LiquidGlassEffect/LiquidGlassEffect";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-montserrat",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Racing Line Portfolio",
  description: "Generated by create next app",
};


export default async function SiteLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${playfair.variable} antialiased`}>
        <LiquidGlassEffect />
        <div className="container mx-auto px-4 md:px-8 lg:px-16">
          <Navbar />
          {children}
        </div>
        <Footer

        />
      </body>
    </html>
  );
}